/*
   addTweet('date X', count Y, 'showPrevious|true|false', `tweetEmbed`);
*/
let _count = 0;
addTweet('12/12', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">12 DE DEZEMBRO DE 2019<br><br>Cientistas chineses detectam um novo surto viral que, apenas no mês seguinte, em referência à oitava cidade mais populosa da China, seria noticiado como “vírus de Wuhan“.<a href="https://t.co/Gn8LviuG1p">https://t.co/Gn8LviuG1p</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967938790760451?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote>`);
addTweet('31/12', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">31 DE DEZEMBRO DE 2019<br><br>Dezenove dias de estudos após a detecção inicial, a China reporta à Organização Mundial de Saúde que uma pneumonia de causa desconhecida fora observada em Wuhan.<a href="https://t.co/kcAqo18GAJ">https://t.co/kcAqo18GAJ</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967941517074432?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote>`);
addTweet('', NaN, '', ``);
addTweet('08/01', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">8 DE JANEIRO DE 2020<br><br>Menos de um mês após a detecção do surto, cientistas chineses descobrem que a pneumonia vinha sendo causada por um novo tipo de coronavírus.</p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967945103183873?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('09/01', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">9 DE JANEIRO DE 2020<br><br>Um senhor de 61 anos que frequentava o Mercado Atacadista de Frutos do Mar de Wuhan é oficialmente a primeira vítima fatal da covid-19. O fato só seria seria noticiado, contudo, dois dias depois.<a href="https://t.co/OxPZEPz8Zc">https://t.co/OxPZEPz8Zc</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967949922381825?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('31/01', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">13 JANEIRO DE 2020<br><br>Com até então apenas 41 casos confirmados na China, um primeiro diagnóstico de covid-19 foi registrado além das fronteiras chinesas. A vítima havia voltado de Wuhan para a Tailândia cinco dias antes.<a href="https://t.co/irhHrE9BNB">https://t.co/irhHrE9BNB</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967952749416448?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
// addTweet('28/01', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">28 DE JANEIRO DE 2020<br><br>Com mais de 4,5 mil casos de covid-19 em todo o mundo, e 106 mortos, Jair Bolsonaro nega ajuda a um grupo de 70 brasileiros que, segundo o Itamaraty, encontrava-se próximo a Wuhan.<a href="https://t.co/P6bozOpshF">https://t.co/P6bozOpshF</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967955664384008?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('28/01', _count, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Após cinco dias, brasileiros que se encontravam na China gravariam um vídeo implorando ajuda. Três dias depois, dois aviões da FAB decolariam para o resgate. Nenhum dos 58 resgatados estava doente.<a href="https://t.co/LkGuS6wj1M">https://t.co/LkGuS6wj1M</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967959330263040?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('30/01', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">30 DE JANEIRO DE 2020<br><br>Com quase 10 mil casos confirmados, e mais de 200 mortes catalogadas em todo o mundo, a OMS declara o surto do novo coronavírus como uma emergência de saúde pública internacional.<a href="https://t.co/FqPCoOdk8t">https://t.co/FqPCoOdk8t</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967962614345735?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('19/02', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">19 DE FEVEREIRO DE 2020<br><br>Didier Raoult, microbiologista francês, em um problemático artigo que se baseia num estudo chinês, espalha que a avaliação clínica confirmara que a cloroquina seria eficaz contra o novo coronavírus.<a href="https://t.co/NpQRak4lg7">https://t.co/NpQRak4lg7</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967966045331464?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
_count = 1;
addTweet('26/02', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">26 DE FEVEREIRO DE 2020<br><br>O Brasil confirma o primeiro caso de covid-19.<a href="https://t.co/PMr8nh4NK0">https://t.co/PMr8nh4NK0</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967970935918595?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('07/03', _count, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Ao menos 23 membros da comitiva voltariam ao Brasil com covid-19.<a href="https://t.co/U6vTjWyVD3">https://t.co/U6vTjWyVD3</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967976879247366?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('08/03', _count, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Por dois meses, contudo, o próprio Bolsonaro faria questão de esconder da imprensa o exame que poderia comprovar a veracidade da segunda versão apresentada pelo terceiro filho do presidente.<a href="https://t.co/b2XSUibYIm">https://t.co/b2XSUibYIm</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967982843539457?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('13/03', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">A Fox News chegaria a noticiar que Jair Bolsonaro também adoecera, mas precisaria voltar atrás após Eduardo Bolsonaro mudar a versão que dera à emissora.<a href="https://t.co/Q3F2KdypwI">https://t.co/Q3F2KdypwI</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967979798454273?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('13/03', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">13 DE MARÇO DE 2020, 151 CASOS<br><br>Com o drama italiano assustando o mundo nos telejornais, as autoridades já defendiam a adoção do isolamento social. Nessa data, algumas escolas brasileiras interrompem as atividades.<a href="https://t.co/zxjYC704ZI">https://t.co/zxjYC704ZI</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967985930555396?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
// addTweet('15/03', _count, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">15 DE MARÇO DE 2020, 162 CASOS<br><br>Ignorando o isolamento social, Jair Bolsonaro participa do primeiro de vários atos golpistas que, aos domingos, contariam com a presença do presidente da República.<a href="https://t.co/4dQROd29VN">https://t.co/4dQROd29VN</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967989197910019?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('15/03', _count, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Ao menos a primeira exibição antidemocrática e contrária às medidas sanitárias recomendadas pelo Ministério da Saúde é feita na companhia de Antonio Barra Torres, presidente da Anvisa.<a href="https://t.co/gRkmkZ0Vip">https://t.co/gRkmkZ0Vip</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967992318484482?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('16/03', _count, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Mesmo com 300 mil casos de covid-19 em todo o mundo, o ensaio de Raoult avaliara apenas vinte, vindo em maio a ser retirado do ar pelos próprios autores sem jamais ser publicado em revista científica.<a href="https://t.co/6n2EaJYla5">https://t.co/6n2EaJYla5</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351967998358253571?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('17/03', _count, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Ignorando as instruções que Luiz Henrique Mandetta dava diariamente na TV, o presidente da República promete receber mais de mil convidados no próprio aniversário.<a href="https://t.co/TyXn0vco9N">https://t.co/TyXn0vco9N</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351968004146343937?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('19/03', 6, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">19 DE MARÇO DE 2020, 6 MORTOS<br><br>Com base no ensaio de Didier Raoult, Donald Trump diz ao mundo que agilizaria a burocracia para que a cloroquina fosse utilizada no combate ao novo coronavírus.<a href="https://t.co/Ki2633Nqfy">https://t.co/Ki2633Nqfy</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351968007191457795?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('20/03', 11, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Diante da inércia do Governo Federal, os governadores estaduais começam a se movimentar contra a pandemia, o que findaria em protestos do presidente da República.<a href="https://t.co/zqSTwhnLae">https://t.co/zqSTwhnLae</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351968014665740291?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
// addTweet('20/03', 11, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Eduardo Bolsonaro, por sua vez, gera uma crise diplomática com a China, provocando uma reação da embaixada chinesa que forçaria um pedido de desculpas do presidente da Câmara Federal.<a href="https://t.co/T0HHhj8CEw">https://t.co/T0HHhj8CEw</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351968018562248708?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('21/03', 15, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Habituado a imitar Donald Trump, o presidente brasileiro anuncia nas redes sociais que ordenara o Exército a aumentar a produção da cloroquina, o medicamento usado contra a malária no Brasil.<a href="https://t.co/Kmpe0Vd87e">https://t.co/Kmpe0Vd87e</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351969285497880576?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('22/03', 25, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">22 DE MARÇO DE 2020, 25 MORTOS<br><br>Jair Bolsonaro chama de exagerados os números do próprio Ministério da Saúde. E, mais uma vez mentindo, espalha que governadores e imprensa estariam ludibriando a opinião pública.<a href="https://t.co/cOqTlG7rTH">https://t.co/cOqTlG7rTH</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351969287918002177?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('24/03', 46, '', `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">24 DE MARÇO DE 2020, 46 MORTOS<br><br>Em pronunciamento na TV, Jair Bolsonaro cinicamente prega contra o isolamento social. Para tanto, alega que, pelo passado de atleta, estaria protegido contra o que novamente chama de “gripezinha“.<a href="https://t.co/gWbVrIPrCN">https://t.co/gWbVrIPrCN</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351969290224852994?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('25/03', 59, true, `<blockquote class="twitter-tweet"><p lang="pt" dir="ltr">Alertado do risco de o Brasil vir a ter 200 mil vítimas fatais da covid-19, Jair Bolsonaro diz que o mundo todo terá no máximo 20 mil mortos.<a href="https://t.co/0DXBsskQo1">https://t.co/0DXBsskQo1</a></p>&mdash; Marlos Ápyus (@apyus) <a href="https://twitter.com/apyus/status/1351969294838624256?ref_src=twsrc%5Etfw">January 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`);
addTweet('date', _count, '', ``);
addTweet('date', _count, '', ``);
addTweet('date', _count, '', ``);
addTweet('date', _count, '', ``);

// _count = 1;
addTweet('2021...', NaN, '', ``);
addTweet('date', 0, '', ``);

/*
   addTweet('date', _count, '', ``);
*/

setPageLayout();